//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agencia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitaciones
    {
        public int id { get; set; }
        public Nullable<int> hotel { get; set; }
        public Nullable<int> tipoHabitacion { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> costo { get; set; }
        public Nullable<double> impuesto { get; set; }
        public Nullable<int> numeroAdultos { get; set; }
        public Nullable<int> numeroNiños { get; set; }
        public Nullable<int> totalPersonas { get; set; }
        public Nullable<int> ubicacion { get; set; }
        public Nullable<int> estado { get; set; }        
        public Nullable<System.DateTime> fechaEntrada { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }

        public virtual Estados Estados { get; set; }
        public virtual Hoteles Hoteles { get; set; }
        public virtual tiposHabitaciones tiposHabitaciones { get; set; }
        public virtual Ubicacion Ubicacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
