//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agencia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AGENCIAModels : DbContext
    {
        public AGENCIAModels()
            : base("name=AGENCIAModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alojamiento> Alojamiento { get; set; }
        public virtual DbSet<contactoEmergencia> contactoEmergencia { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Habitaciones> Habitaciones { get; set; }
        public virtual DbSet<Hoteles> Hoteles { get; set; }
        public virtual DbSet<Reservas> Reservas { get; set; }
        public virtual DbSet<tiposDocumentos> tiposDocumentos { get; set; }
        public virtual DbSet<tiposHabitaciones> tiposHabitaciones { get; set; }
        public virtual DbSet<Ubicacion> Ubicacion { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
