//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agencia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reservas
    {       
        public int id { get; set; }
        public Nullable<int> usuario { get; set; }
        public Nullable<int> hotel { get; set; }
        public Nullable<int> habitacion { get; set; }
        [Required]
        public Nullable<System.DateTime> fechaEntrada { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
        [Required]
        public string ciudadDestino { get; set; }
        public Nullable<int> cantidadPersonas { get; set; }
        [Required]
        public string nombreEmergencia { get; set; }
        [Required]
        public string apellidoEmergencia { get; set; }
        [Required]
        public string telefomoEmergencia { get; set; }
        public Nullable<int> estado { get; set; }

        public string nombre_hotel { get; set; }
        public string nombre_habitacion { get; set; }
        public string nombre_usuario { get; set; }

        public virtual Estados Estados { get; set; }
        public virtual Hoteles Hoteles { get; set; }        
        public virtual Usuarios Usuarios { get; set; }
        public virtual Habitaciones Habitaciones { get; set; }
    }
}
