//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agencia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int id { get; set; }
        public Nullable<int> alojamiento { get; set; }
        public Nullable<int> contactoEmergencia { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual Alojamiento Alojamiento1 { get; set; }
        public virtual contactoEmergencia contactoEmergencia1 { get; set; }
        public virtual Estados Estados { get; set; }
    }
}
