//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agencia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {           
            this.Reservas = new HashSet<Reservas>();            
        }
        public int id { get; set; }
        public Nullable<int> tipoDocumento { get; set; }
        public string numeroDocumento { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string email { get; set; }
        public Nullable<int> genero { get; set; }
        public string telefono { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string nombreUsuario { get; set; }
        public string clave { get; set; }
        public Nullable<int> rol { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual Generos Generos { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual tiposDocumentos tiposDocumentos { get; set; }
        //public virtual Reservas Reservas { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
